#To check the null values in the data

In [1]:
import pandas as pd

In [4]:
data = {
    "Name" : ["Ali", "Sara", "Amjad", "Ayesha", "Noor"],
    "Age": [20, None, 21, None, 22],
    "English": [35, 43, None, None, 50],
    "Maths": [None, 45, 65, 23, None],
}
a=pd.DataFrame(data)
a

     Name   Age  English  Maths
0     Ali  20.0     35.0    NaN
1    Sara   NaN     43.0   45.0
2   Amjad  21.0      NaN   65.0
3  Ayesha   NaN      NaN   23.0
4    Noor  22.0     50.0    NaN

In [ ]:
#a.dropna() -->remove all the entries having null values.
#To check the null values in data
a.isnull().sum()

Name       0
Age        2
English    2
Maths      2
dtype: int64

In [6]:
#to fill the default values to make data clean and clear
b=a.fillna({"Age": 25, "English": 20, "Maths": 40})
b

     Name   Age  English  Maths
0     Ali  20.0     35.0   40.0
1    Sara  25.0     43.0   45.0
2   Amjad  21.0     20.0   65.0
3  Ayesha  25.0     20.0   23.0
4    Noor  22.0     50.0   40.0

In [7]:
#Convert tabular data into CSV file.
b.to_csv("student.csv", index=False)

In [8]:
#To read the file
c=pd.read_csv("student.csv")
c

     Name   Age  English  Maths
0     Ali  20.0     35.0   40.0
1    Sara  25.0     43.0   45.0
2   Amjad  21.0     20.0   65.0
3  Ayesha  25.0     20.0   23.0
4    Noor  22.0     50.0   40.0